import {
  SiAndroidstudio,
  SiAngular,
  SiArduino,
  SiCplusplus,
  SiCss3,
  SiDart,
  SiDocker,
  SiFirebase,
  SiFlutter,
  SiGit,
  SiGo,
  SiGraphql,
  SiHtml5,
  SiJavascript,
  SiKotlin,
  SiMongodb,
  SiMysql,
  SiNextdotjs,
  SiPostgresql,
  SiPython,
  SiReact,
  SiRedis,
  SiSolid,
  SiSpringboot,
  SiSupabase,
  SiTailwindcss,
  SiTrpc,
  SiTypescript,
} from "@icons-pack/react-simple-icons";
import { IconFileUnknown } from "@tabler/icons-react";

export const skills = {
  git: { name: "Git", rating: 5, icon: <SiGit size={40} color="default" /> },
  docker: {
    name: "Docker",
    rating: 4,
    icon: <SiDocker size={40} color="default" />,
  },
  html: {
    name: "HTML",
    rating: 5,
    icon: <SiHtml5 size={40} color="default" />,
  },
  css: { name: "CSS", rating: 5, icon: <SiCss3 size={40} color="default" /> },
  tailwindcss: {
    name: "Tailwind CSS",
    rating: 5,
    icon: <SiTailwindcss size={40} color="default" />,
  },
  javascript: {
    name: "JavaScript",
    rating: 5,
    icon: <SiJavascript size={40} color="default" />,
  },
  typescript: {
    name: "TypeScript",
    rating: 5,
    icon: <SiTypescript size={40} color="default" />,
  },
  react: {
    name: "React",
    rating: 4,
    icon: <SiReact size={40} color="default" />,
  },
  nextjs: { name: "Next.js", rating: 5, icon: <SiNextdotjs size={40} /> },
  angular: { name: "Angular", rating: 3, icon: <SiAngular size={40} /> },
  solidjs: {
    name: "SolidJS",
    rating: 1,
    icon: <SiSolid size={40} color="default" />,
  },
  kotlin: {
    name: "Kotlin",
    rating: 3,
    icon: <SiKotlin size={40} color="default" />,
  },
  android: {
    name: "Android Studio",
    rating: 3,
    icon: <SiAndroidstudio size={40} color="default" />,
  },
  dart: { name: "Dart", rating: 2, icon: <SiDart size={40} color="default" /> },
  flutter: {
    name: "Flutter",
    rating: 2,
    icon: <SiFlutter size={40} color="default" />,
  },
  python: {
    name: "Python",
    rating: 4,
    icon: <SiPython size={40} color="default" />,
  },
  go: { name: "Go", rating: 2, icon: <SiGo size={40} color="default" /> },
  java: { name: "Java", rating: 2, icon: <IconFileUnknown size={40} /> },
  spring: {
    name: "SpringBoot",
    rating: 3,
    icon: <SiSpringboot size={40} color="default" />,
  },
  c: {
    name: "C++",
    rating: 3,
    icon: <SiCplusplus size={40} color="default" />,
  },
  arduino: {
    name: "Arduino",
    rating: 2,
    icon: <SiArduino size={40} color="default" />,
  },
  firebase: {
    name: "Firebase",
    rating: 4,
    icon: <SiFirebase size={40} color="default" />,
  },
  supabase: {
    name: "Supabase",
    rating: 4,
    icon: <SiSupabase size={40} color="default" />,
  },
  redis: {
    name: "Redis",
    rating: 3,
    icon: <SiRedis size={40} color="default" />,
  },
  mongodb: {
    name: "MongoDB",
    rating: 4,
    icon: <SiMongodb size={40} color="default" />,
  },
  mysql: {
    name: "MySQL",
    rating: 3,
    icon: <SiMysql size={40} color="default" />,
  },
  postgres: {
    name: "PostgreSQL",
    rating: 3,
    icon: <SiPostgresql size={40} color="default" />,
  },
  rest: {
    name: "REST",
    rating: 5,
    icon: <IconFileUnknown size={40} />,
  },
  graphql: {
    name: "GraphQL",
    rating: 2,
    icon: <SiGraphql size={40} color="default" />,
  },
  gaphql: {
    name: "tRPC",
    rating: 2,
    icon: <SiTrpc size={40} color="default" />,
  },
};
